resources:
  # Volumes
  - arthur-global-data.yml

  # Applications
  - apps/galahad.yml
  - apps/gradekeeper-server.yml
  - apps/streamapps-server.yml
  - apps/streamapps-shim.yml
  - apps/jacksonbot.yml
  # - apps/nextcloud.yml
  # - apps/identity.yml
